# Generated by Django 2.2.4 on 2019-08-05 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='utilaje')),
            ],
        ),
        migrations.CreateModel(
            name='UtilajDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('utilaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Utilaj')),
            ],
        ),
    ]
