# Generated by Django 2.2.4 on 2019-08-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilaj',
            options={'verbose_name': 'Utilaj', 'verbose_name_plural': 'Utilaje'},
        ),
        migrations.AlterModelOptions(
            name='utilajdescription',
            options={'verbose_name': 'Descriere Utilaj', 'verbose_name_plural': 'Descriere Utilaje'},
        ),
        migrations.RemoveField(
            model_name='utilaj',
            name='image',
        ),
        migrations.AddField(
            model_name='utilaj',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UtilajImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='utilaje')),
                ('utilaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Utilaj')),
            ],
            options={
                'verbose_name': 'Imagine Utilaj',
                'verbose_name_plural': 'Imagini Utilaj',
            },
        ),
        migrations.CreateModel(
            name='UtilajCaracteristici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos')),
                ('pdf', models.FileField(upload_to='pdfs')),
                ('utilaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Utilaj')),
            ],
            options={
                'verbose_name': 'Caracteristici Utilaj',
                'verbose_name_plural': 'Caracteristici Utilaj',
            },
        ),
    ]
