# Generated by Django 2.2.4 on 2019-08-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190805_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilajcaracteristici',
            options={'verbose_name': 'Caracteristici Utilaj', 'verbose_name_plural': 'Caracteristici Utilaje'},
        ),
        migrations.AlterModelOptions(
            name='utilajimage',
            options={'verbose_name': 'Imagine Utilaj', 'verbose_name_plural': 'Imagini Utilaje'},
        ),
    ]
