# Generated by Django 2.2.4 on 2019-08-05 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190806_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilajimage',
            name='utilaj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilaj_image', to='product.Utilaj'),
        ),
    ]
