# Generated by Django 2.2.4 on 2019-08-06 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190806_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='firme_logos')),
                ('pdf', models.FileField(upload_to='firme_pdfs')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firme',
            },
        ),
        migrations.CreateModel(
            name='UtilajPropriu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='utilaje_proprii_images')),
            ],
            options={
                'verbose_name': 'Utilaj Propriu',
                'verbose_name_plural': 'Utilaje Proprii',
            },
        ),
        migrations.CreateModel(
            name='UtilajPropriuDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('utilaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilaj_propriu_descriptions', to='product.UtilajPropriu')),
            ],
            options={
                'verbose_name': 'Descriere Utilaj Propriu',
                'verbose_name_plural': 'Descrieri Utilaj Propriu',
            },
        ),
        migrations.CreateModel(
            name='UtilajVanzare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='utilaje_vanzare_pdfs')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Firma')),
            ],
            options={
                'verbose_name': 'Utilaj de Vanzare',
                'verbose_name_plural': 'Utilaje de Vanzare',
            },
        ),
        migrations.CreateModel(
            name='UtilajVanzareDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('utilaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilaj_vanzare_descriptions', to='product.UtilajVanzare')),
            ],
            options={
                'verbose_name': 'Descriere Utilaj de Vanzare',
                'verbose_name_plural': 'Descrieri Utilaj de Vanzare',
            },
        ),
        migrations.CreateModel(
            name='UtilajVanzareImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='utilaje_vanzare_images')),
                ('utilaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilaj_vanzare_image', to='product.UtilajVanzare')),
            ],
            options={
                'verbose_name': 'Imagine Utilaj de Vanzare',
                'verbose_name_plural': 'Imagini Utilaj de Vanzare',
            },
        ),
        migrations.RemoveField(
            model_name='utilajcaracteristici',
            name='utilaj',
        ),
        migrations.RemoveField(
            model_name='utilajdescription',
            name='utilaj',
        ),
        migrations.RemoveField(
            model_name='utilajimage',
            name='utilaj',
        ),
        migrations.DeleteModel(
            name='Utilaj',
        ),
        migrations.DeleteModel(
            name='UtilajCaracteristici',
        ),
        migrations.DeleteModel(
            name='UtilajDescription',
        ),
        migrations.DeleteModel(
            name='UtilajImage',
        ),
    ]
